---

- name: Install dependencies
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - java

- name: Install jMeter from URL
  unarchive:
    src: "{{jmeter_software_url}}"
    dest: /home/jmeter/
    copy: no
    creates: "/home/jmeter/apache-jmeter-{{jmeter_software_version}}/bin"